apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-js-deployment
  labels:
    app: react-js
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-js
  template:
    metadata:
      labels:
        app: react-js
    spec:
      containers:
      - name: react-js
        image: nginx # Match this with the Jenkinsfile image name and tag
        ports:
        - containerPort: 80
---

